### ISSUE TITLE
Add support for setting --version from command line

### ISSUE THREAD

**Issue by maguro** [ahmetb/govvv#11]
Forcing people to use the `./VERSION` file seems to be a bit arbitrary.  Especially if pre-existing tooling pipelines don't support it.  It would be nice if there was something like a `--version` option to set this value.

**Comment by ahmetb** [comment]
Sounds like a good feature request. I'm currently working on other stuff, so it will take me a while to get to this. Would you mind working on it? I can help out during the process.

**Comment by maguro** [comment]
Sure, I can work on this.

**Comment by ahmetb** [comment]
Fixed in #14 .
