### ISSUE TITLE
make the logic into a package so others can call it

### ISSUE THREAD

**Issue by ghost** [ahmetb/govvv#15]
Would be nicer with a pkg, so i can use this as part of CI.
Still have the main of course for users using it from the command line.

**Comment by ahmetb** [comment]
The project alone is fairly trivial to copy, so I didn't go down this route initially. 

What are you expecting to get out of the package? How will you be using it from CI? If you can describe your use case, maybe I can understand better.

**Comment by ghost** [comment]
At compile time locally and in c I want to ask ithe package for the git
hash etc , rather than use a shell script.
But I wanted to call it from my own golang code.

Your right too in that I can just copy the code.

It's probably best I do but I wanted to let you have the option to do it if
you want.

**Comment by ahmetb** [comment]
I'm mostly shelling out to commands like `git rev-parse --short HEAD` to get the commit hash. 

https://github.com/ahmetb/govvv/blob/eeed55f64b034cbb8d82676030f98676e1b4dae1/git.go

I think you should just do an `import "os/exec"; ... hash := exec.Command("git", "rev-parse", "--short","HEAD").Output()` yourself.

**Comment by ghost** [comment]
thats what i am doing too.
Will go with your suggestion.  thanks
