### ISSUE TITLE
stoped working after upgrade to go1.11

### ISSUE THREAD

**Issue by d2k** [ahmetb/govvv#17]
Hi, 

govvv worked fine with older go version. But
go version go1.11 windows/amd64 now returns

govvv build .\testGit.go
go tool: fork/exec C:\Go\bin\go.exe: invalid argument

go build .\testGit.go works fine 

//test program
package main

import "log"

var GitCommit, GitBranch, GitState, BuildDate, Version string

func main() {

	log.Println("Code Status at compile time: ")
	log.Println("   Version:   " + Version)
	log.Println("   GitCommit: " + GitCommit)
	log.Println("   GitBranch: " + GitBranch)
	log.Println("   GitState:  " + GitState)
	log.Println("   BuildDate: " + BuildDate)
}

**Comment by ahmetb** [comment]
Can you run it with `-print` (see readme for example)? This would print the go cmd that is executed.

**Comment by d2k** [comment]
it is odd - the printed version works but the govvv build doesnt...

```
~$ go build  ./testGit.go
~$ govvv build  ./testGit.go
go tool: fork/exec /usr/bin/go: invalid argument
~$ govvv build  -print ./testGit.go
go build \
        -ldflags \
        "-X main.GitSummary=c673a20-dirty -X main.Version='\xff\xfe0\x00.\x000\x00.\x001\x00\r\x00\n\x00' -X main.BuildDate=2018-09-12T06:19:04Z -X main.GitCommit=c673a20 -X main.GitBranch=master -X main.GitState=dirty" \
        ./testGit.go
~$ go build \
>         -ldflags \
>         "-X main.GitSummary=c673a20-dirty -X main.Version='\xff\xfe0\x00.\x000\x00.\x001\x00\r\x00\n\x00' -X main.BuildDate=2018-09-12T06:19:04Z -X main.GitCommit=c673a20 -X main.GitBranch=master -X main.GitState=dirty" \
>         ./testGit.go
~$ ./testGit
2018/09/12 08:19:28 Code Status at compile time:
2018/09/12 08:19:28    Version:   '\xff\xfe0\x00.\x000\x00.\x001\x00\r\x00\n\x00'
2018/09/12 08:19:28    GitCommit: c673a20
2018/09/12 08:19:28    GitBranch: master
2018/09/12 08:19:28    GitState:  dirty
2018/09/12 08:19:28    BuildDate: 2018-09-12T06:19:04Z
~$
```

the example is from a ubuntu shell on Windows 10 but powershell on Windows 10 has the same behaviour...

**Comment by ahmetb** [comment]
I edited your response because it was hard to read (I recommend using the code block buttons on github)

Arguably your version string looks a bit weird. Do you have a `VERSION` file that has emojis or something? Or is it big endian format? Clearly govvv is reading some non-ASCII characters.

I have no other idea why this might be broken or windows machine to test this. :) Attempting to debug would be a simple exercise for anyone interested.

**Comment by d2k** [comment]
Yes, it was the VERSION file.
It was odd. When I opened it in VI I saw 0.0.1 as expected but a more showed only 0. 
Editing in VI doesn't solve the issue. I needed to delete and create a new one.
But now it works on Windows and Linux Bash.
Thx!
