### ISSUE TITLE
Work with spf13/cobra - customise package name

### ISSUE THREAD

**Issue by ghost** [ahmetb/govvv#18]
[cobra](https://github.com/spf13/cobra#create-additional-commands) can generate applications quickly.

However, it puts commands in a cmd package instead of main. 
This means that govvv can't be used because it requires package main.

Given that govvv sets a few global variables, it should still work even if the package name was not main. The assumption of course, is that a package name of "not main" is intentional.

Therefore, it would be nice if a flag could be specified that changed the package name govvv uses from main to something else, example: `-package cmd`

**Comment by ahmetb** [comment]
I assume you missed the `-pkg` flag. See the readme: https://github.com/ahmetb/govvv/tree/eeed55f64b034cbb8d82676030f98676e1b4dae1#want-to-use-a-different-package

**Comment by ghost** [comment]
I did. Thank you!
