### ISSUE TITLE
govvv bump?

### ISSUE THREAD

**Issue by kirillDanshin** [ahmetb/govvv#3]
Hi.
Can you add `govvv bump patch`, `govvv bump minor`, `govvv bump major` commands?
So we can bump patch/minor/major version with govvv.

**Comment by ahmetb** [comment]
Well, where do you store your version number for govvv to find out? :-)

**Comment by kirillDanshin** [comment]
`VERSION` file

**Comment by ahmetb** [comment]
Hmm govvv is a go tool wrapper. I don't think it should do another job via a subcommand, such as bumping a version file. I'm a bit against this idea for now.
