### ISSUE TITLE
If no version provided what about use GitSummary as VERSION?

### ISSUE THREAD

**Issue by codeskyblue** [ahmetb/govvv#4]

**Comment by ahmetb** [comment]
@codeskyblue that's not a bad idea at all. However a developer of a project would know which one to pick, and if they find `GitSummary` suitable, they can just use it in their program?

The problem with `GitSummary` is, it picks up all tags. So for example if you're making docs releases for your project using separate tags, we have no generic way of saying only `--match v[0-9\.]+$`, so you might end up with a weird tag name like `docs-v2.1.0` in `GitSummary`.

**Comment by codeskyblue** [comment]
Use regexp match is a good way(seems). Before see your repo, I build my go project use a shell script

``` sh
!/bin/bash -

set -eu

VERSION=$(git describe --abbrev=0 --tags)
REVCNT=$(git rev-list --count HEAD)
DEVCNT=$(git rev-list --count $VERSION)
if test $REVCNT != $DEVCNT
then
        VERSION="$VERSION.dev$(expr $REVCNT - $DEVCNT)"
fi
echo "VER: $VERSION"

GITCOMMIT=$(git rev-parse HEAD)
BUILDTIME=$(date -u +%Y/%m/%d-%H:%M:%S)

LDFLAGS="-X main.VERSION=$VERSION -X main.BUILDTIME=$BUILDTIME -X main.GITCOMMIT=$GITCOMMIT"
if [[ -n "${EX_LDFLAGS:-""}" ]]
then
        LDFLAGS="$LDFLAGS $EX_LDFLAGS"
fi

build() {
        echo "$1 $2 ..."
        GOOS=$1 GOARCH=$2 go build \
                -tags bindata \
                -ldflags "$LDFLAGS" \
                -o dist/gohttpserver-${3:-""}
}

build linux arm linux-arm
build darwin amd64 mac-amd64
build linux amd64 linux-amd64
build linux 386 linux-386
build windows amd64 win-amd64.exe
```

The version is come from

``` sh
VERSION=$(git describe --abbrev=0 --tags)
REVCNT=$(git rev-list --count HEAD)
DEVCNT=$(git rev-list --count $VERSION)
if test $REVCNT != $DEVCNT
then
        VERSION="$VERSION.dev$(expr $REVCNT - $DEVCNT)"
fi
```

**Comment by ahmetb** [comment]
@codeskyblue so I believe the `GitSummary` variable today  is pretty usable as is if you're using tags only to release versions of your repository. (if you don't agree, let me know) and if your project does not have a VERSION file (which is something you already know as the developer of the project), then you'd just use `GitSummary` variable and not `Version`, right?

**Comment by codeskyblue** [comment]
No, I don't agree, usally version can be found in tags, so why have to write a VERSION file. However you are the owner of this repo, if you don't agree I can fork it and make my own.

**Comment by ahmetb** [comment]
@codeskyblue VERSION file is optional. If `GitSummary` field is enough for you, why not just use it? I just did not get your point. :-)

**Comment by codeskyblue** [comment]
GitSummary is summary, it got the different meaning of version. Not just name, because next month when you review your code, you will be wired, and say what is the `GitSummary` and where is version?

**Comment by ahmetb** [comment]
Oh I see your point. You're right we could offer GitSummary as Version if the file does not exist. I tend to agree that ideally tags should be used correctly however they rarely are used correctly.

I think since the project is not so much adopted just yet, we can consider implementing it so that GitSummary is assigned to Version if the file does not exist. Would you consider contributing it?

**Comment by codeskyblue** [comment]
Yes, ofcourse, anyway, I need to use such tool
