### ISSUE TITLE
Feature:  option to specify package in which to set variables

### ISSUE THREAD

**Issue by mmindenhall** [ahmetb/govvv#7]
Setting the variables in the `main` package unfortunately means that they're only visible within `main`.  If I want to use them elsewhere (e.g., display version info in a web page built from my `httpsrv` package), I have to duplicate the variables in another package, and set them when my application starts.

Therefore, I'd like an option to specify the package where I want the variables set.  For example:

```
$ govvv -pkg version -flags
-X github.com/myaccount/myproject/version.GitState=dirty -X github.com/myaccount/myproject/version.GitSummary=f693f40-dirty -X github.com/myaccount/myproject/version.Version=1.7.5 -X github.com/myaccount/myproject/version.BuildDate=2016-10-18T16:33:47Z -X github.com/myaccount/myproject/version.GitCommit=f693f40 -X github.com/myaccount/myproject/version.GitBranch=staging
```

&nbsp;

IMHO, this would be the ideal behavior -- being able to pass `version` as the argument, and having the tool substitute the full package name (which is required for this to work).  But I'd also be fine with just passing the full package name (e.g., `github.com/myaccount/myproject/version`) as the argument.

I can probably work on this and submit a PR if you like.

**Comment by ahmetb** [comment]
@mmindenhall I'm open to PRs. I expected this feature request to come at some point.

We can introduce a `-pkg` argument. But govvv should not resolve `pkgname` into `github.com/full/pkgname`. This is what `go list` command is for. You can use it as:

```
$ govvv -pkg $(go list ./version) ...
```

We can maybe shell out to `go list` internally in the future, if `$(go list ./name)` syntax looks hard to use with govvv (I doubt it).

**Comment by maguro** [comment]
Having `govvv` shell out to `go list` internally seems like mixing concerns.  I suspect that most will hard code the value and those that can't have to deal with intricacies of their local CI pipeline where `go list` may not be the appropriate thing to do.

**Comment by maguro** [comment]
This can be closed now, no?
